// Code generated by mockery v2.20.0. DO NOT EDIT.

package utils_mocks

import mock "github.com/stretchr/testify/mock"

// AuthProvider is an autogenerated mock type for the AuthProvider type
type AuthProvider struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: uid
func (_m *AuthProvider) GenerateToken(uid string) (string, error) {
	ret := _m.Called(uid)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyToken provides a mock function with given fields: tokenStr
func (_m *AuthProvider) VerifyToken(tokenStr string) (string, error) {
	ret := _m.Called(tokenStr)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(tokenStr)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthProvider creates a new instance of AuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthProvider(t mockConstructorTestingTNewAuthProvider) *AuthProvider {
	mock := &AuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
