// Code generated by mockery v2.20.0. DO NOT EDIT.

package utils_mocks

import mock "github.com/stretchr/testify/mock"

// EncryptionProvider is an autogenerated mock type for the EncryptionProvider type
type EncryptionProvider struct {
	mock.Mock
}

// Decrypt provides a mock function with given fields: _a0
func (_m *EncryptionProvider) Decrypt(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypt provides a mock function with given fields: _a0
func (_m *EncryptionProvider) Encrypt(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewEncryptionProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewEncryptionProvider creates a new instance of EncryptionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEncryptionProvider(t mockConstructorTestingTNewEncryptionProvider) *EncryptionProvider {
	mock := &EncryptionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
