// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	secrets "github.com/adarsh-a-tw/passwordly/secrets"
	mock "github.com/stretchr/testify/mock"
)

// SecretRepository is an autogenerated mock type for the SecretRepository type
type SecretRepository struct {
	mock.Mock
}

// CreateCredential provides a mock function with given fields: secret, credential
func (_m *SecretRepository) CreateCredential(secret *secrets.Secret, credential *secrets.Credential) error {
	ret := _m.Called(secret, credential)

	var r0 error
	if rf, ok := ret.Get(0).(func(*secrets.Secret, *secrets.Credential) error); ok {
		r0 = rf(secret, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSecretRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewSecretRepository creates a new instance of SecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecretRepository(t mockConstructorTestingTNewSecretRepository) *SecretRepository {
	mock := &SecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
