// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	vaults "github.com/adarsh-a-tw/passwordly/vaults"
	mock "github.com/stretchr/testify/mock"
)

// SecretRepository is an autogenerated mock type for the SecretRepository type
type SecretRepository struct {
	mock.Mock
}

// CreateCredential provides a mock function with given fields: secret, credential
func (_m *SecretRepository) CreateCredential(secret *vaults.Secret, credential *vaults.Credential) error {
	ret := _m.Called(secret, credential)

	var r0 error
	if rf, ok := ret.Get(0).(func(*vaults.Secret, *vaults.Credential) error); ok {
		r0 = rf(secret, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindCredentialById provides a mock function with given fields: credential, credentialId
func (_m *SecretRepository) FindCredentialById(credential *vaults.Credential, credentialId string) error {
	ret := _m.Called(credential, credentialId)

	var r0 error
	if rf, ok := ret.Get(0).(func(*vaults.Credential, string) error); ok {
		r0 = rf(credential, credentialId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindSecretById provides a mock function with given fields: secret, secretId
func (_m *SecretRepository) FindSecretById(secret *vaults.Secret, secretId string) error {
	ret := _m.Called(secret, secretId)

	var r0 error
	if rf, ok := ret.Get(0).(func(*vaults.Secret, string) error); ok {
		r0 = rf(secret, secretId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSecretRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewSecretRepository creates a new instance of SecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecretRepository(t mockConstructorTestingTNewSecretRepository) *SecretRepository {
	mock := &SecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
